{% set name = "libzenohcxx" %}
{% set version = "1.6.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/eclipse-zenoh/zenoh-cpp/archive/refs/tags/{{ version }}.tar.gz
    sha256: 9527b968ed06d17525fa35604dec41e4fe9e486d6d3ad684074c3e962422a008
    patches:
      - nowerror.patch

build:
  number: 0
  # See https://github.com/conda-forge/zenoh-c-feedstock/issues/37
  skip: true  # [ppc64le]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
  host:
    - libzenohc {{ version }}.*

test:
  commands:
    - test -f ${PREFIX}/include/zenoh.hxx  # [unix]
    - if not exist %LIBRARY_PREFIX%\\include\\zenoh.hxx exit 1  # [win]
    - cmake-package-check zenohc zenohcxx --targets zenohcxx zenohcxx::zenohc
  requires:
    - cmake-package-check
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

about:
  home: https://github.com/eclipse-zenoh/zenoh-cpp
  license: Apache-2.0 OR EPL-2.0
  license_file: LICENSE
  summary: C++ API for zenoh

extra:
  feedstock-name: zenoh-cpp
  recipe-maintainers:
    - traversaro
