{% set name = "libzenohcxx" %}
{% set version = "1.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/eclipse-zenoh/zenoh-cpp/archive/refs/tags/{{ version }}.tar.gz
    sha256: c4975b998afafc478a97ed5b6d5f57ed082ae8d2e56aedd8040e62cc45969d13

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
  host:
    - libzenohc {{ version }}.*

test:
  commands:
    - test -f ${PREFIX}/include/zenoh.hxx  # [unix]
    - if not exist %LIBRARY_PREFIX%\\include\\zenoh.hxx exit 1  # [win]
    - cmake-package-check zenohc zenohcxx --targets zenohcxx zenohcxx::zenohc
  requires:
    - cmake-package-check
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

about:
  home: https://github.com/eclipse-zenoh/zenoh-cpp
  license: Apache-2.0 OR EPL-2.0
  license_file: LICENSE
  summary: C++ API for zenoh

extra:
  feedstock-name: zenoh-cpp
  recipe-maintainers:
    - traversaro
